# Documentation - Set and Show API formats.
# feature_name:
#     api_method_name:
#         apis:
#             - [Application,Version.1||Version.2]

analyticsconfig:
    select_source:
        apis:
            - [xmc,'8.2.5']
