# Documentation - Set and Show API formats.
# feature_name:
#     api_method_name:
#         apis:
#             - [Application,Version.1||Version.2]

configurations:
    configs_aaa_default_check_authenticate_for:
        apis:
            - [emc,'8.1.3']
    configs_aaa_default_select_auth_methods:
        apis:
            - [emc,'8.1.3']
    configs_aaa_default_select_primary_radius_server:
        apis:
            - [emc,'8.1.3']
    configs_aaa_default_select_backup_radius_server:
        apis:
            - [emc,'8.1.3']
    configs_aaa_default_select_ldap_configuration:
        apis:
            - [emc,'8.1.3']
    configs_aaa_default_select_local_password_repository:
        apis:
            - [emc,'8.1.3']
    configs_aaa_default_save_aaa_default:
        apis:
            - [emc,'8.1.3']
    configs_aaa_default_cancel_aaa_default:
        apis:
            - [emc,'8.1.3']
    configs_click_add_access_control_configuration_button:
        apis:
            - [emc,'8.1.3']
    configs_click_delete_access_control_configuration_button:
        apis:
            - [emc,'8.1.3']
    configs_click_edit_access_control_configuration_button:
        apis:
            - [emc,'8.1.3']
    configs_click_select_aaa_configuration_button:
        apis:
            - [emc,'8.1.3']
    configs_select_aaa_configuration_dialog_select_aaa_configuration:
        apis:
            - [emc,'8.1.3']
    configs_select_access_control_configuration:
        apis:
            - [emc,'8.1.3']
    configs_add_access_control_configuration:
        apis:
            - [emc,'8.1.3']
    configs_delete_access_control_configuration:
        apis:
            - [emc,'8.1.3']
    configs_rules_click_add_rule_button:
        apis:
            - [emc,'8.3.0']
    configs_rules_click_delete_rule_button:
        apis:
            - [emc,'8.3.0']
    configs_rules_click_edit_rule_button:
        apis:
            - [emc,'8.3.0']
    configs_rules_select_rule:
        apis:
            - [emc,'8.3.0']
    configs_rules_dialog_delete_rule:
        apis:
            - [emc,'8.3.0']
    configs_rules_dialog_enable_rule:
        apis:
            - [emc,'8.3.0']
    configs_rules_click_refresh_button:
        apis:
            - [emc,'8.3.0||8.4.0']
    configs_rules_dialog_add_rule:
        apis:
            - [emc,'8.3.0||8.4.0']
