# ### Documentation - Set and Show API formats. ###
# feature_name:
#     api_set_method_name:
#         description: Information about the keyword function.
#         uuid: uuid from https://www.uuidgenerator.net/version1
#         arguments:
#             order: arg2,arg3,arg1
#         apis:
#             CLI:
#                 - [OS1,Platform,Version,Unit,Command,Prompt,PromptArgs,ConfirmationPhrases,ConfirmationArgs,IgnoreError,AddError]
#                 - [OS2,Platform,Version,Unit,Command,Prompt,PromptArgs,ConfirmationPhrases,ConfirmationArgs,IgnoreError,AddError]
#             REST:
#                 - [OS1,Platform,Version,Unit,Request Type,URI,Headers,Ignore Error String,Add Error String]
#             SNMP:
#                 - [OS1,Platform,Version,Unit,SNMP Command Type,OID,SNMP Data Type,Value]
#     api_show_method_name:
#         apis:
#             CLI:
#                 - [OS1,Platform,Version,Unit,Command,Prompt,PromptArgs,ConfirmationPhrases,ConfirmationArgs,IgnoreError,AddError]
#                 - [OS2,Platform,Version,Unit,Command,Prompt,PromptArgs,ConfirmationPhrases,ConfirmationArgs,IgnoreError,AddError]
#             REST:
#                 - [OS1,Platform,Version,Unit,Request Type,URI,Headers,Ignore Error String,Add Error String]
#             SNMP:
#                 - [OS1,Platform,Version,Unit,SNMP Command Type,OID,SNMP Data Type,Value]

site:
    show_all:
        uuid: 66054fea-36d6-49b3-a59a-c64727a94ad6
        apis:
            CLI:
                - [EXTRWIRELESS,base,baseversion,baseunit,'show site',userPrompt,'None','None','None',[],[]]
    show_detail:
        uuid: cb810be3-6e9d-48c1-878e-915722ddbf33
        apis:
            CLI:
                - [EXTRWIRELESS,base,baseversion,baseunit,'show site "{site_name}"',userPrompt,'None','None','None',[],[]]
