# pip
robotframework:
  version: "3.0"
  pkg_mgr: "pip"
  description: "A generic test automation framework"
robotframework-debuglibrary:
  version: "0.8"
  pkg_mgr: "pip"
  description: "RobotFramework debug library and an interactive shell"
robotframework-selenium2library:
  version: "1.8.0"
  pkg_mgr: "pip"
  description: "Web testing library for Robot Framework"
robotframework-extendedselenium2library:
  version: "0.9.1"
  pkg_mgr: "pip"
  description: "Extended Selenium2 web testing library for Robot Framework with AngularJS support"
python-ostinato:
  version: "0.8"
  pkg_mgr: "pip"
  description: "python-ostinato provides python bindings for the Ostinato network packet/traffic generator and analyzer"
pyshark:
  version: "0.3.6.1"
  pkg_mgr: "pip"
  description: "Python wrapper for tshark, allowing python packet parsing using wireshark dissectors"
PyYAML:
  version: "3.12"
  pkg_mgr: "pip"
  description: "YAML parser and emitter for Python"
pysnmp:
  version: "4.3.2"
  pkg_mgr: "pip"
  description: "A cross-platform, pure-Python SNMP engine implementation"
paramiko:
  version: "2.1.1"
  pkg_mgr: "pip"
  description: "SSH2 protocol library"
psutil:
  version: "5.0.0"
  pkg_mgr: "pip"
  description: "psutil is a cross-platform library for retrieving information onrunning processes and system utilization (CPU, memory, disks, network)in Python."
netmiko:
  version: "1.1.0"
  pkg_mgr: "pip"
  description: "Multi-vendor library to simplify Paramiko SSH connections to network devices"
selenium:
  version: "3.0.2"
  pkg_mgr: "pip"
  description: "portable software-testing framework for web applications"
ipaddress:
  version: "1.0.17"
  pkg_mgr: "pip"
  description: "IPv4/IPv6 manipulation library"
httplib2:
  version: "0.9.2"
  pkg_mgr: "pip"
  description: "A comprehensive HTTP client library"
cryptography:
  version: "1.7.1"
  pkg_mgr: "pip"
  description: "cryptography is a package which provides cryptographic recipes and primitives to Python developers"
requests:
  version: "2.12.4"
  pkg_mgr: "pip"
  description: "Python HTTP for Humans"
scp:
  version: "0.10.2"
  pkg_mgr: "pip"
  description: "scp module for paramiko"
pyvmomi:
  version: "6.5"
  pkg_mgr: "pip"
  description: "VMware vSphere Python SDK"
six:
  version: "1.10.0"
  pkg_mgr: "pip"
  description: "Python 2 and 3 compatibility utilities"
Flask:
  version: "0.12.2"
  pkg_mgr: "pip"
  description: "Python REST Api Builder"
Flask-Cors:
  version: "3.0.3"
  pkg_mgr: "pip"
  description: "Required for HTTPS flask apps"
xmlrunner:
  version: "1.7.7"
  pkg_mgr: "pip"
  description: "XML report generator for python unittests."
pyserial:
  version: "3.4"
  pkg_mgr: "pip"
  description: "Module for utilizing serial connections."

# apt
python:
  version: "2.7.11-2"
  pkg_mgr: "apt"
  description: "interactive high-level object-oriented language (default version)"
python-tk:
  version: "2.7.11-2"
  pkg_mgr: "apt"
  description: "Tkinter - Writing Tk applications with Python"
python-dev:
  version: "2.7.11-2"
  pkg_mgr: "apt"
  description: "Header files and a static library for Python (v2.7)"
python-software-properties:
  version: "0.96.24.7.1"
  pkg_mgr: "apt"
  description: "manage the repositories that you install software from"
oracle-java8-installer:
  version: "8.0"
  pkg_mgr: "apt"
  description: "Java development platform"
  comments: "Need to add repo to update apt: sudo add-apt-repository ppa:webupd8team/java"
git:
  version: "2.12.2"
  pkg_mgr: "apt"
  description: "fast, scalable, distributed revision control system"


# NOT SURE IF NEEDED:
libxml2-dev:
  version:
  pkg_mgr: "apt"
  description:
libxslt1-dev:
  version:
  pkg_mgr: "apt"
  description:
MySQL-python:
  version:
  pkg_mgr: "pip"
  description: