# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  automation-dev-env:
    image: ghcr.io/extremenetworks/extreme_automation_framework/automation-dev-env:latest
    container_name: automation-dev-env
    environment:
      - RESOLUTION=1920x1080
    deploy:
      resources:
        limits:
          memory: 5G
        reservations:
          memory: 5G
    volumes:
      - C:/automation/git:/automation
      - C:/automation/home:/root
      - /dev/shm:/dev/shm
    ports:
      - "5901:5900"
      - "7900:80"
      - "2200:22"
    depends_on:
       - chrome
       - firefox
    networks:
      - grid

  chrome:
    image: selenium/node-chrome:4.1.2-20220131
    container_name: selenium-hub-chrome
    shm_size: 2gb
#    volumes:
#      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
      - "7901:7900"
    networks:
      - grid

  firefox:
    image: selenium/node-firefox:4.1.2-20220131
    container_name: selenium-hub-firefox
    shm_size: 2gb
#    volumes:
#      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"
      - "7902:7900"
    networks:
      - grid

  selenium-hub:
    image: selenium/hub:4.1.2-20220131
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - grid
      
networks:
  grid:
